ClimateImpactLab/dodola

dodola/repository.py

`dodola.repository.RepositoryABC` was roughly defined. This PR fills our the ABC and docstrs with hints about dev direction for this interface.

Flesh out RepositoryABC, docstrs

---

.github/workflows/test.yaml

Close #3 
This fix was created in response to no CI feedback in PR #2.

Trigger CI on PR to main or push

---

.github/workflows/buildpush.yaml
.github/workflows/container.yaml
.github/workflows/test.yaml
Dockerfile
environment.yaml
requirements.txt
setup.py

Fixes issues with failing CI/CD. Uses `conda` for virtual environment. CI/CD now works on Docker container, aside from code quality checks.
Close #11

Swap in conda env and more container-based CI/CD workflows

---

dodola/cli.py

This PR fixes the bug described in #32.

fix buildweights bug

---

dodola/cli.py

This PR is a quick bug fix for #34. 
Close #34

fix cli bug

---

dodola/cli.py

Fix so we don't have such a ridiculous amount of 3rd party logging output to stdout. Close #45.

Add naive log hushing

---

environment.yaml

New xarray release with relevant changes to zarr chunking. We'll want to play with these updates.

Unpin xarray dependency

---

HISTORY.rst
dodola/core.py
dodola/tests/test_services.py
environment.yaml

Fix CMIP6 clean to better handle coords vs dims

---

environment.yaml

This PR pins package versions in the Docker container conda environment.
This is a stability check in prep for the next release.

Pin environment packages in prep for release

---

HISTORY.rst
dodola/core.py
dodola/tests/test_core.py

Fix bug in dodola.services.train_quantiledeltamapping() accounting for endpoints

---

HISTORY.rst
dodola/cli.py
dodola/core.py
dodola/services.py
dodola/tests/test_services.py

Not much to say. This change includes a test for the new behavior and internal documentation update. 
This is a simple workaround to #91.
Close #91

Add astype arg to regrid(s)

---

dodola/tests/test_services.py

This PR adds testing for the multiplicative `kind` for the AIQPD training and integration tests. 
closes #112

add multiplicative testing to aiqpd train test

---

Dockerfile
HISTORY.rst

Rolling with the updates. The base image has not been upgraded in some time.

Upgrade Docker base image to continuumio/miniconda3:4.10.3

---

.github/PULL_REQUEST_TEMPLATE.md

Adds a template to pester our contributor and ensure they note changes in HISTORY.rst.

Internal: Add PR template for GH

---

.github/PULL_REQUEST_TEMPLATE.md

history tracker is no longer HISTORY.rst but CHANGELOG.md

---

CHANGELOG.md
README.md

Our README was really bad before. This PR updates it with something a little bit better.
Expect more PRs to clean things up further.

Begin to fill-out README.md

---

.github/workflows/buildpush.yaml

Add job to CI/CD, pushing `dev` container to GHCR.

Add push dev to GHCR

---

CHANGELOG.md
environment.yaml

Upate container conda environment package pins. We are pretty behind and they're in need of an update.

Remove conda package pins

---

dodola/core.py
dodola/services.py

Very minor format cleanup to fix new version of black being moody (e.g. PR #248).

Minor format cleanup for newer version of black

---

CHANGELOG.md

[summarize your pull request here]

Fix bad release links in CHANGELOG
