ClimateImpactLab/dodola

- dodola/cli.py
- dodola/core.py
- dodola/services.py
- dodola/tests/test_services.py
- requirements.txt
- setup.py
This PR adds in some super basic bias correction code as well as a dependency on a forked version of scikit-downscale with an interim fix for a current bug in PointwiseDownscaler.
> first attempt at adding basic bias correction code and fixing tests

- .dockerignore
- Dockerfile
- requirements.txt
- setup.py
Biggest change here is the addition of files needed to containerize the application.
Building and testing this locally with:
```shell
docker build --tag dodola:dev .
docker run dodola:dev pytest -v --pyargs dodola
```
Additional changes:
- Add `pytest` to requirements.txt so can test package within container.
- Drop `setuptools_scm` package from `setup_requires`. We're not using `setuptools_scm` for package versioning anyways and this might create problems for container build without a network.
Close #6
> Add initial Dockerfile build config

- .github/workflows/container.yaml
Adds a new Github Actions workflow to build, test, and push a Docker container image to a private container registry. This workflow is triggered on pushes to `main`.
Close #8.
> Add initial container-based CICD workflow

- dodola/cli.py
- dodola/repository.py
- dodola/services.py
- dodola/tests/test_repository.py
- environment.yaml
Adds `dodola.repository.AzureZarr`, giving us basic support to stream Zarr files to and from Azure Data Lake Gen2 storage.
This authenticates with storage account keys or service credentials via environment variables. For storage account key authentication set `AZURE_STORAGE_ACCOUNT` and `AZURE_STORAGE_KEY`.
Alternatively, for service principals authentication, set `AZURE_CLIENT_ID`, `AZURE_CLIENT_SECRET`, and `AZURE_TENANT_ID`.
There is also an option to just set credentials at the command line.
With storage credentials set to environment variables, call `biascorrect` from the CLI with:
```
dodola biascorrect cleanstore/input.zarr cleanstore/training.zarr cleanstore/obs.zarr productstore/output.zarr
```
Other changes:
- Add tests for a repository subclass.
- Clean out old, unused …
> Add prototype support for Azure Data Lake Gen2 storage

- dodola/cli.py
- dodola/core.py
- dodola/repository.py
- dodola/services.py
- dodola/tests/test_cli.py
- dodola/tests/test_services.py
- environment.yaml
This is a rough pass at weights-file building functionality. I also set up logging.
This adds:
- CLI interface: `dodola buildweights <inputfile_url> -m "bilinear" --output /new-weightsfile.nc`
- `build_weights()` in `dodola/services.py`.
- `build_xesmf_weights_file()` in `dodola/core.py` - Does the work, returns the weights file path.
- `xesmf` is now a dependency.
- Tests to check that service outputs a file where we tell it to. Checks that the CLI doesn't give an error if someone tries to run `dodola buildweights --help`.
- We now have services logging so we have a basic record of whats happening, when. Trying to keep it simple and see how it goes.
You can pick whichever regridding method you want and this is passed on to `xesmf`. This also lets `xesmf` handle errors and input checks …
> Add ESMF weights file-building service, logging

- dodola/cli.py
- dodola/core.py
- dodola/services.py
- dodola/tests/test_services.py
- environment.yaml
This PR updates the core bias correction code to include the QDM method (Cannon et al., 2015) by specifying the bias correction method at the CLI interface. 
Specifically, it adds: 
- CLI interface: `dodola biascorrect <method> <methodstring> <inputURL> <modeltrainingURL> <obstrainingURL> <outputURL>`
- updates `bias_correct_bcsd` to `apply_bias_correction` to support both BCSD and QDM by including a `method` argument
- updates `apply_bias_correction` to include QDM code 
- `xclim` is now a dependency
- testing is still with BCSD since we don't have a way to test both methods currently 
closes #18
> add QDM as bias correction option

- Dockerfile
- dodola/cli.py
- dodola/core.py
- dodola/repository.py
- dodola/services.py
- dodola/tests/test_cli.py
- dodola/tests/test_repository.py
- dodola/tests/test_services.py
- environment.yaml
Adds rechunking service via the `rechunker` package. It lets us rechunk a single variable in zarr store.
CLI interface is:
```bash
dodola rechunk path/to/a/store.zarr -v tasmax \
-c time=31390 \
-c lat=30 \
-c lon=30 \
--maxmemory 113004000 \
--out path/to/rechunked/store.zarr
```
The logic for rechunking sits entirely within `dodola/services.py` because we're letting the `chunker` package do all the work and `chunker` is tightly coupled to the data model and storage details. We've been trying to keep the data model out of the `dodola/core.py`.
This refactors `dodola/repository.py` into a single class `_ZarrRepo` which users use/instantiate through functions `memory_repository()` and `adl_repository()` (formerly known as `FakeRepository` and `AzureZarr`). These instances behave like they …
> Add rechunker service, refactor repository.py to simplify

- dodola/cli.py
- dodola/services.py
Log services with the new `@log_service` decorator. Now developers don't need to put logging statements in their service functions. Close #22
Moved all storage authentication into `dodola.cli._authenticate_storage()`. It just pull credentials from environment variables. This reduces tedious (but important!) repetition and makes `dodola/cli.py` little less cluttered. Close #23
> Add decorator-based service logging, clean CLI storage authentication

- dodola/services.py
Fixes a bug that made debugging from tests and CI/CD very difficult.
This should be high priority to merge. This is also my bad. The solution keeps things very simple.
Close #30
> Fix exception catching in logging decorator

- dodola/cli.py
- dodola/core.py
- dodola/services.py
- dodola/tests/test_cli.py
- dodola/tests/test_services.py
Adds service to regrid zarr files with `xesmf`.
Basic interface from CLI is 
```bash
dodola regrid /path/to/store.zarr \
--out /path/to/regrid.zarr \
--method "bilinear"
```
Can use `-r`/`--targetresolution` to set the target global grid resolution (1.0 x 1.0 is default). Can use `-w`/`--weightspath` to use to any precalculated regridding weights in a NetCDF file on disk.
Includes integration test to ensure regridding works with pre-computed regridding weights from `dodola buildweights`.
Close #27.
> Add service for regridding zarrs

- environment.yaml
This is complicated but, `adlfs` <= 0.7 requires `fsspec` <= 0.9. Otherwise it tries to import things that arn't there and breaks our CI/CD. See the closed issue for more details.
close #53
> Fix bad ffspec, adlfs imports

- dodola/cli.py
Our CLI help for `dodola rechunk` says we should be passing in `maxmem` as bytes. This PR ensures this is cast as `int` and not a `str`, which `rechunker` doesn't seem to like.
This PR does not change the `dodola rechunk` CLI. Pure bug fix.
close #48
> Cast CLI option to int, fix rechunker maxmem error

- HISTORY.rst
- dodola/cli.py
- dodola/repository.py
- dodola/services.py
- dodola/tests/test_services.py
- environment.yaml
Swaps our `rechunker`-based rechunking for more memory-intensive (but stable) `xarray`-based rechunking.
This PR makes breaking changes to `dodola rechunk`, dropping the `variable` and `maxmemory` options. Similar breaking changes in `dodola.services.rechunk()`, notably `target_chunks` is now just a mapping of coordinate to their rechunk size.
Internally, also dropped the `get_mapper()` method from `dodola.respository` because it's not needed. `rechunker` support was the only need.
Close #57
> Use simple xarray rechunking

- HISTORY.rst
- dodola/cli.py
- dodola/repository.py
- dodola/services.py
- dodola/tests/test_repository.py
- dodola/tests/test_services.py
- environment.yaml
With this PR just about all data inputs need to be `fsspec` URLs. All storage authentication gets passed through fsspec-storage backend default environment variables. `dodola.services` functions no longer require the `storage` arg. 
In short, we spec storage with URLs like:
```
dodola cleancmip6 az://raw/gfdl.zarr az://clean/gfdl.zarr
```
Storage is authenticated completely through input `fsspec` URLs on a data-by-data basis. This means functions requiring multiple input data can read the data from different `fsspec` backends.
In terms of package architecture, storage I/O (`dodola/repository.py`) would now happen in `dodola/services.py`. `dodola/core.py` and notably `dodola/cli.py`. Both are now decoupled from storage logic.
`dodola` will accept URLs for S3 (via `s3fs`) and GCS buckets …
> Require fsspec URLs, refactor

- HISTORY.rst
- dodola/cli.py
Get this when running the new `dodola rechunk`:
```
dc6-dev-djdj6-3755863106: Traceback (most recent call last):
dc6-dev-djdj6-3755863106:   File "/opt/conda/bin/dodola", line 33, in <module>
dc6-dev-djdj6-3755863106:     sys.exit(load_entry_point('dodola', 'console_scripts', 'dodola')())
dc6-dev-djdj6-3755863106:   File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 829, in __call__
dc6-dev-djdj6-3755863106:     return self.main(*args, **kwargs)
dc6-dev-djdj6-3755863106:   File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 782, in main
dc6-dev-djdj6-3755863106:     rv = self.invoke(ctx)
dc6-dev-djdj6-3755863106:   File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
dc6-dev-djdj6-3755863106:     return …
```
> Fix TypeError in dodola.cli.py::rechunk

- HISTORY.rst
- dodola/cli.py
- dodola/core.py
- dodola/services.py
- dodola/tests/test_services.py
This PR adds domain file functionality to the `build_weights` service and is _not_ backwards compatible with previous versions of the service. 
CLI interface is now: 
```
dodola buildweights <inputfile_url> -m "bilinear" --domain_file <domain_file_url> --output /new-weightsfile.nc
```
closes #49
> add domain file functionality to buildweights

- HISTORY.rst
- dodola/cli.py
- dodola/core.py
- dodola/services.py
- dodola/tests/test_services.py
- environment.yaml
This PR adds a downscaling service (currently only spatial disaggregation) and removes the BCSD option from the bias correction service.
Basic interface from CLI is
```
dodola downscale /path/to/store.zarr \
--trainvariable tasmax \
--yclimocoarse /path/to/obsclimocoarse.zarr \
--yclimofine /path/to/obsclimofine.zarr \
--out /path/to/regrid.zarr \
--outvariable tasmax \
--method "BCSD" \
--domain_file /path/to/domainfile/zarr \
--adjustmentfactors /path/to/af.zarr
```
`--adjustmentfactors` is an optional argument to specify a path if the user wants to write adjustment factors to a zarr, and `weightspath` an optional argument to specify a path to weights if they have been precomputed for use in regridding from coarse to fine. 
closes #51
> Add downscaling service

- Dockerfile
- HISTORY.rst
- dodola/repository.py
Minor additions to make runs easier to debug.
- When run in "debug" mode, will log any path/URL to be opened or written to, before any attempt is made. -- This is helpful because bad zarr paths are not printed in error messages.
- Remove stdout buffering from running Docker container by default.
> Make runs easier to debug

- environment.yaml
This removed esmpy pin was required for xesmf to function. Several updates and builds have been released since.
> Drop indirect dependency pin

- environment.yaml
This PR updates our pin on the `xclim@sdba-ufunc` to grab the most recent commit.
We don't need this bump for a specific new feature or bug fix, but we want to track and test the latest updates to this branch.
> Bump xclim@sdba-ufunc version to latest commit

- HISTORY.rst
- dodola/cli.py
- dodola/core.py
- dodola/services.py
- dodola/tests/test_cli.py
- dodola/tests/test_services.py
This PR adds a wet day frequency correction service. 
The wet day frequency method follows the Cannon et al 2015 method: motivated by the mixed discrete continuous nature of precip data, dry days are treated as values below a set threshold (in that paper, 0.05 mm/day). Zero values in the observed and modeled data are replaced with nonzero uniform random values below the threshold before bias correction; after bias correction (and downscaling in our case), all values below the threshold are set to zero. The pre and post bias correction options are denoted here with `pre-process` and `post-process` CLI options. 
Basic CLI interface is: 
```
dodola correct-wetday-frequency /path/to/store.zarr \
--out /path/to/corrected.zarr \
--process "pre-process" / "post-process"
```
closes #40
> add wet day frequency correction

- environment.yaml
We pinned to a previous release of the `dask` package because it broke recent releases of `xarray`. With recent upgrades to the current release of `xarray` and `dask` should be compatible. This PR unpins `dask` so we can test on the latest release of the package before we do a new release.
> Update docker environment's dask install

- Dockerfile
- HISTORY.rst
- environment.yaml
Couple nuts-n-bolts changes here:
* Makes the `dodola` command the container's default CMD. This is just sugar when running the `dodola` container. By default, it'll now assume that you're running the `dodola` command unless you say otherwise.
* Adds `dask-kubernetes`, `distributed` to container environment. So these are not always installed from scratch. They're starting to get used in prototype workflows.
* Improves subprocess, signal, and death handling in Docker container — this is important as we start to do more process-heavy prototypes.
Close #89
> Add dask-kubernetes, distributed, and better subprocess handling in container

- HISTORY.rst
- dodola/cli.py
- dodola/core.py
- dodola/services.py
- dodola/tests/test_core.py
- environment.yaml
This PR adds quantile information to bias corrected output to be used in analog-inspired downscaling with a new `include_quantiles` flag that can be passed to `apply_qdm`. If `include_quantiles` is set to `True`, there will be a `sim_q` coordinate on `scen` in the bias corrected output that can be used in the analog-inspired downscaling method. 
closes #86
> Add analogdownscaling qdm options

- HISTORY.rst
- dodola/core.py
- dodola/tests/test_services.py
This PR adds a units conversion for precip to the CMIP6 cleaning service and updates the test suite a bit such that the unit conversion can be tested. 
closes #93
> Add precip unit conversion

- environment.yaml
Pinning a loose `xclim` package version in prep for the next release.
Related to #97.
> Pin xclim version in environment

- HISTORY.rst
- environment.yaml
These dependencies are not directly required or used outside of dev. Removing in prep for release.
Can put the packages in after the next release if we want them for dev and future features. This is just cleaning up non-essential cruft.
> Drop explicit distributed, dask-kubernetes

- HISTORY.rst
- dodola/cli.py
Close #103.
Also drops the logging for `gcfs` to WARNING. It is otherwise too chatty with DEBUG runs.
> Fix application logging to stdout

- HISTORY.rst
- environment.yaml
Minor version upgrade to `xclim`.
Also notes reason for `pandas` pin. Close #97.
> Bump xclim to v0.28.0, improve environment notes

- HISTORY.rst
- environment.yaml
`intake-esm` is used in docker container scripts for raw CMIP6 download. `papermill` is used to automate notebook runs.
These additions do not relate to the `dodola` application. Beware. They may be removed before the next release.
> Add papermill, intake-esm to docker environment

- HISTORY.rst
- dodola/cli.py
- dodola/core.py
- dodola/services.py
- dodola/tests/test_core.py
Can now call
```bash
dodola regrid ... --cyclic "lon"
```
to add cyclic points (aka wrap-around pixels) to the "lon" dimension before regridding.
This is the `add_cyclic` option for `dodola.services.regrid`.
Close #107.
> Add --cyclic option to regrid cli and services

- HISTORY.rst
- environment.yaml
Jumping this gap is better done sooner rather than later because it makes `consolidate=True` the default with Zarr I/O.
> Bump container environment to xarray to v0.19.0

- HISTORY.rst
- dodola/cli.py
- dodola/core.py
- dodola/services.py
- dodola/tests/test_cli.py
- dodola/tests/test_core.py
- dodola/tests/test_services.py
- environment.yaml
This PR adds the analog-inspired, quantile-preserving downscaling method as a new service. It is split up into two services, `train_aiqpd` and `adjust_aiqpd` and is based on the implementation of QDM. This is intended to supersede spatial disaggregation as the main mode of downscaling in `dodola` for the time being. 
Basic CLI interface is: 
```
dodola train_aiqpd /path/to/coarse_reference.zarr \
/path/to/fine_reference.zarr 
--out /path/to/trained_afs.zarr \
--v "tasmax", 
--k "+"
```
```
dodola apply_aiqpd /path/to/biascorrected.zarr \
/path/to/trainedafs/zarr \
-- year 2026
--v "tasmax" 
--out /path/to/trained_afs.zarr \
```
closes #73
> Add analog downscaling prototype

- dodola/cli.py
- dodola/core.py
- dodola/services.py
- dodola/tests/test_services.py
Updates `adjust` step in the AIQPD downscaling method (breaking backwards compatibility), updates `train` test and adds AIQPD integration test between QDM and AIQPD services. 
New `adjust` interface is: 
```bash
dodola apply-aiqpd --simulation /path/to/biascorrected.zarr \
--aiqpd /path/to/adjustfactors.zarr \
-v "tasmax" 
--out /path/to/adjusted.nc \
```
closes #111 and #113
> AIQPD to operate on full timeseries, add aiqpd_adjust test

- HISTORY.rst
- dodola/core.py
- dodola/services.py
- dodola/tests/test_core.py
- dodola/tests/test_services.py
- environment.yaml
Update `xclim` version to 0.30.1 in our fork, adds support for 360-day calendars. 
This PR also adds `breaking` changes for the QDM and AIQPD implementations to make them consistent with the major `xclim` 0.29 updates and requires that all inputs to QDM and AIQPD have units attributes that are compatible with `pint` units.
> update xclim version after merging in newest xclim changes

- HISTORY.rst
- dodola/cli.py
- dodola/core.py
- dodola/services.py
- dodola/tests/test_core.py
- dodola/tests/test_services.py
This PR adds `--iselslice` and `--selslice` to `train-qdm` and `train-aiqpd` (and their twins in`dodola.services`).
This means you can do something like
```bash
dodola --debug train-qdm -v "tasmax" \
-h "gs://scratch-170cd6ec/biascorrectdownscale-fqpdn/biascorrectdownscale-fqpdn-1975355103/rechunked.zarr" \
-r "gs://scratch-170cd6ec/biascorrectdownscale-fqpdn/biascorrectdownscale-fqpdn-4235871458/rechunked.zarr" \
-k "additive" \
--iselslice "lat=170,180" \
--out "/home/cooluser/Downloads/dodola_test.zarr"
```
and it will slice the data with `xr.Dataset.isel` before the model is trained.
This feature is helpful for larger, automated, orchestrated that don't use an external dask distributed scheduler, or train a larger dataset in local memory.
Some shoddy, but effective tests are included …
> Add pre-training slicing options to train-qdm and train-aiqpd

- HISTORY.rst
- dodola/core.py
Validation tries to read entire Zarr stores into memory to perform some checks.
This PR implements the work-around in https://github.com/ClimateImpactLab/downscaleCMIP6/blob/0122ce6730de73c6b64b8e9ca120e2bfaf95e7bb/workflows/templates/qualitycontrol-check-cmip6.yaml#L47 as a quick fix to the problem. Basically reading annual slices through via dask.delayed.
> Quick fix validation reading entire zarr store for QC check

- HISTORY.rst
- dodola/services.py
Fixes bug from: 'ValueError: ... Multiple chunks along the main adjustment dimension time is not supported' when running `dodola train-aiqpd`. 
We get this from running the new `dodola train-aiqpd` in legacy workflows. Ideally, we'd resolve this by changing chunking in upstream workflow steps, but `train_aiqpd` was written so we would not need to address these kinds of breaking changes until a later time. In other words, `train_aiqpd` needs to support bad input dataset chunking to support legacy. This PR fixes it so that it does so.
> Fix ValueError from chunks in time in existing workflows

- HISTORY.rst
- dodola/cli.py
- dodola/core.py
- dodola/repository.py
- dodola/services.py
- dodola/tests/test_cli.py
- dodola/tests/test_services.py
This PR rewrites the QDM command prototypes, breaking backward compatibility.
Changes include:
- New command for priming a Zarr Store so it can be written to regionally by independent processes. For example:
```bash
dodola prime-qdm-output-zarrstore \
--simulation "gs://path/to/file/we/want/to/biascorrect.zarr" \
--variable "tasmax" \
--years "2015,2100" \
--out "gs://path/to/where/we/want/biascorrected/to/go.zarr" \
--zarr-region-dims "lat"
```
We should then be set to write output to that zarr store, regionally, with regions delimited along the "lat" dimension.
- Write to regions of a primed Zarr Store aggressively with `dodola apply-qdm --out-zarr-region`. For example, `--out-zarr-region "lat=0,2"` will write QDM-adjusted output to `slice(0, 2)` along the "lat" dimension. Note this is …
> Add QDM output Zarr priming, region writing, metadata, multi-year processing

- HISTORY.rst
- dodola/cli.py
- dodola/core.py
- dodola/services.py
- dodola/tests/test_cli.py
- dodola/tests/test_services.py
Sibling to #129 but for priming AIQPD and `apply-aiqpd`. See #129 for details.
This is breaks backward compatibility.
> Add AIQPD output Zarr priming, slicing, region writing, metadata, multi-year processing

- HISTORY.rst
- dodola/cli.py
- dodola/services.py
- dodola/tests/test_cli.py
- dodola/tests/test_services.py
Adds a `dodola get-attrs` command with tests and services.
Used like:
```bash
dodola get-attrs gs://path/to/store.zarr
```
will give a JSON str of the zarr stores global attrs in STDOUT.
```bash
dodola get-attrs gs://path/to/store.zarr --variable tasmax
```
will fetch the attrs for the "tasmax" variable.
> Add `dodola get-attrs` command

- HISTORY.rst
- dodola/cli.py
- dodola/repository.py
- dodola/services.py
- dodola/tests/test_repository.py
Add `--root-attrs-json-file` option to let users specify an ffsspec-style URL to a JSON file when can be read and used for the output data's root attrs as an alternative to the input files attrs. 
This will make it easier for users who want to overhaul a rediculous amount of common metadata across multiple steps.
This option was added for commands:
- `prime-qplad-output-zarrstore`
- `apply-qplad`
- `prime-qdm-output-zarrstore`
- `apply-qdm`
`--new-attrs` are applied _after_ JSON attrs are read in and used.
> Add qdm, qplad option to set root attrs from json

- HISTORY.rst
- dodola/core.py
Previously, root attrs were missing from dodola.services.apply_qplad output Dataset. This PR fixes the root of the problem, in core.adjust_analogdownscaling, so that it correctly passes input Dataset root attrs to returned output.
> Fix attrs missing from services.apply_qplad output Datasets

- HISTORY.rst
- dodola/tests/test_core.py
This PR adds a rough integration test to check that adjustment factors and quantiles are matched and applied correctly in `dodola.core.adjust_analogdownscaling` and `dodola.core.train_analogdownscaling`.
> Add additional integration tests for dodola.core.*_analogdownscaling functions

- HISTORY.rst
- dodola/core.py
This PR bumps the dtr validation to accept ranges to accept dtr values up to 70 degrees C. This is up from 40 degrees. It's based on ranges we found in a preliminary survey of CMIP6 GCMs.
> Update dtr range check max to 70 C

- dodola/core.py
- environment.yaml
This PR updates analog downscaling naming in xclim, the associated class name here (`AnalogQuantilePreservingDownscaling` --> `QuantilePreservingAnalogDownscaling`) and updates the xclim version to the latest commit.
> update xclim analog downscaling method name and version

- HISTORY.rst
- dodola/core.py
@dgergel this is solving https://github.com/ClimateImpactLab/dodola/issues/139. We're (1) raising an exception if the time span is too short, with a slightly lower expectation for `'future' 'cmip6'` (2) warning the user if the time span is too long.
@brews I don't think there is a test to write, but let me know if I am wrong.
> distinguish missing from excess timesteps in timesteps validation

- HISTORY.rst
- dodola/cli.py
- dodola/services.py
@brews this is related to https://github.com/ClimateImpactLab/downscaleCMIP6/issues/182. It adds a `--wet-day-post-correction` option to the `click` `apply-qplad` command, which we will then want to use in the `apply-qplad` template.
> click wetday correction

- HISTORY.rst
- dodola/core.py
Raising the validation limit for tasmax because a few models have max values that are slightly higher than this (they go up to 355K for MIROC6 ssp585 and 351K for KIOST-ESM). This is _extremely_ high, but I think we want to keep as is for now.
> update temp range max to 360K

- HISTORY.rst
- dodola/core.py
This PR updates validation of the number of timesteps in a bias corrected or downscaled output file to account for models that end in 2099 versus 2100. 
Addresses the issue with some models https://github.com/ClimateImpactLab/downscaleCMIP6/issues/383
> Update biascorrection validation

- HISTORY.rst
- dodola/cli.py
- dodola/core.py
- dodola/services.py
- dodola/tests/test_services.py
This PR adds a new service for correcting diurnal temperature range values below a threshold. Since this function will only be used for DTR, the threshold is defined within the `core` function and is not an input argument. We can change this later if desired. 
Used as: 
```
dodola correct-dtr /path/to/dtr_to_correct.zarr \
--out /path/to/corrected_dtr.zarr
```
This will then be added to the DTR downscaling workflow and will solve https://github.com/ClimateImpactLab/downscaleCMIP6/issues/380.
> add dtr correction for small dtr values

- HISTORY.rst
- dodola/cli.py
- dodola/core.py
- dodola/services.py
- dodola/tests/test_core.py
This solves #125, (precip units incompatible with the `xclim` `pint` registry)
1. added an `units_replacement` parameter to each `services.apply-*` and `services.train-*` function, to (optionally) temporarily swap the `variable` `units` attribute for a chosen string, during bias correction and downscaling. 
2. this option is used in each upstream `cli` function if `variable=='pr'` to temporarily swap units with `"mm/day"`. 
@brews (1) is general (variable agnostic) in case we want to make use of that in other cases, but (2) doesn't give an option and uses it for precip -- so that we don't need to change workflow templates _now_. I didn't write a unit test, it sounded like a lot of code to me for what it is. I am not fully aware of our test coverage ambitions though. Let me know.
> precip units temporary replacement

- HISTORY.rst
- dodola/core.py
- dodola/services.py
Solves chunking errors by loading the input Dataset into memory before cleaning/standardizing.
Close #149
> Fix 360 day calendar conversion chunk errors from dodola.services.clean_cmip6

- HISTORY.rst
- dodola/core.py
Differentiates validation of DTR ranges based on polar regions. 
addresses the bug mentioned here: https://github.com/ClimateImpactLab/downscaleCMIP6/issues/450
> update DTR validation ranges

- .github/workflows/test.yaml
- Makefile
This adds a Makefile. This hopefully make the testing and linting more transparent to contributors who want to run these locally. Use like:
```
make format-check
make test
make format
```
Changes GH Actions workflows so it uses this for code-quality check.
> Internal: Add Makefile, use for CI workflow

- CHANGELOG.md
- dodola/core.py
- dodola/tests/test_services.py
Updates the wet day frequency correction to 1) correct very small negative values, 2) limit the "corrected" range to  `threshold*10^-2` to the threshold (which we set to 0.05 mm) to prevent values from blowing up. 
Also updates the precip validation code a bit to be more useful when it fails. 
see https://github.com/ClimateImpactLab/downscaleCMIP6/issues/458 for additional context
> Update wdf correction

- CHANGELOG.md
- dodola/core.py
Update WDF correction further to avoid precip values "blowing up"
> Further updates to wdf correction

- CHANGELOG.md
- dodola/core.py
- dodola/tests/test_services.py
This PR updates the WDF correction with additions from the ISI-MIP WDF correction method outlined in Hempel et al 2013 (https://esd.copernicus.org/articles/4/219/2013/esd-4-219-2013.html). 
Three key changes are made: 
- raises threshold to 1mm (from Hempel et al 2013)
- applies correction to values _below_ the threshold, not just to zeroes 
- raises "low" value in uniform distribution to threshold / 2
These changes are made to address the ongoing challenges of applying a WDF correction at a global scale and having mismatched dry days in the reference and model output, resulting in some precip values being physically unrealistic.
> update WDF correction with Hempel et al 2013 additions

- CHANGELOG.md
- dodola/cli.py
- dodola/core.py
- dodola/services.py
- dodola/tests/test_services.py
This PR adds a maximum precipitation adjustment service so that maximum precipitation values above a threshold get adjusted to that threshold. 
CLI interface is: 
```
dodola adjust_maximum_precipitation /path/to/precip_to_correct.zarr \
--out /path/to/corrected_precip.zarr
-t 3000.0
```
This will then be added to the e2e precip downscaling workflow (no related issues to list at this time). 
Note: this also updates the maximum validation precip threshold to 3000 mm (from its previous max of 2000mm).
> Add max precip ceiling

- CHANGELOG.md
- dodola/cli.py
- dodola/core.py
- dodola/services.py
- dodola/tests/test_services.py
- #468, #470, #472, #473, #474, #475, #476, #477, #481 from https://github.com/ClimateImpactLab/downscaleCMIP6/issues
- rename the DTR correction core function to 'floor...'
- added an equivalent one for a ceiling only applied to [-60, 60]. Default ceiling is 70. 
-  merged these two functionalities in one service renamed to correct_dtr
- added tests for the latter 
-  accordingly modified click 
- changed `<` to `<=` in the DTR range validation 
This means our DTR 'validation' looses its meaning from when the DTR correction is applied on. It's a quick-and-dirty fix. 
@dgergel this is just applying a cap at 70. This follows what I saw in the data (data points away from 60th north parallel but with a value significantly larger than 70) and me realizing (1) that 60th north parallel already …
> floor and ceiling for DTR

- dodola/core.py
- dodola/tests/test_services.py
This corrects a bug introduced by https://github.com/ClimateImpactLab/dodola/pull/165. 
In the DTR ceiling we were making use of direct comparison operators like `or` etc... Which lead to a typical error with arrays. 
This was not caught by the tests because there was only _one_ latitude coordinate. 
Changes : 
- switched to `xr.ufuncs` logical operators
- enhanced tests by using arrays with with several latitude coordinates. 
I am not doing anything to the changelog because this is just an extension of #165.
> corrected DTR ceiling boolean expression and tests accordingly

- CHANGELOG.md
- dodola/core.py
- dodola/services.py
- removed the excess logging messages from #143. Those are in 'excess' because are duplicates : they inform about something happening in a subsequent call to a function, every time this call happens. 
- therefore, I replaced those by a single `logger.info` message happening within this given function. Did that for both cf -> pint function and vice versa.
> Remove excess unit conversion info logging

- CHANGELOG.md
- dodola/core.py
This decreases the lower bound of the temperature validation window from 150 to 130 Kelvin to let in the pipeline an isolated extreme value from the raw ACCESS-ESM1 historical data. As noted here, this extreme value does not seem to be indicative of a general problem with that GCM.
> extend minimum temperature tolerance from 150 K to 130 K

- CHANGELOG.md
- dodola/core.py
- dodola/services.py
- dodola/tests/test_services.py
essential changes : 
- in the core function, instead of using a unique replacement value, use an array of (likely) different values, in `process='pre'`
- values _strictly_ below 1 are modified, rather than below or equal to 1, in `process='pre'`. 
- make tests deterministic (with a `seed`), smaller and more precise. 
secondary changes : 
2. in the core function, directly operate on the data array object within the dataset -- which means I have to introduce a `var` parameter -- default value is `'pr'`, but in tests we have other variable names. Need that parameter in the service as well.
> Fix wetday frequency correction

- CHANGELOG.md
- dodola/core.py
In this PR:
* Tiny patch, setting dtype of np.random.uniform to match variable in wet day frequency correction
> include dtype in np.random.uniform addressing #175

- CHANGELOG.md
- dodola/core.py
This fixes a few object reference mistakes in `dodola.core.standardize_gcm`, that were causing https://github.com/ClimateImpactLab/downscaleCMIP6/issues/439 but could have been in general more problematic. 
In the beginning of the function, a new transformed dataset object named `ds_cleaned` is created out of `ds`, but in subsequent calls, there are remaining references to `ds` where we should reference the transformed object instead. 
This fix mechanically solves /ClimateImpactLab/downscaleCMIP6/issues/439 (which I verified in this workflow : https://argo.cildc6.org/archived-workflows/default/6da813ba-47ba-45a0-95d8-36444e2bcf7b), because we actually drop the time bounds in `ds_cleaned`, which were causing the issue.
> fix bad references 

- CHANGELOG.md
- dodola/core.py
- dodola/services.py
@brews there is more detailed background information in https://github.com/ClimateImpactLab/downscaleCMIP6/issues/574, but here I summarize it : 
This PR directly modifies a previous one that had breaking changes : https://github.com/ClimateImpactLab/dodola/pull/151
Back then, the change was to load the data in memory in `dodola.services.clean_cmip6`, to fix chunking problems in the case where in the underlying `dodola.core.standardize_gcm`, `calendar == 360_day`. 
We observe in https://github.com/ClimateImpactLab/downscaleCMIP6/issues/574 that this PR broke runs with data that's too large for our nodes and the downstream computations. 
My suggested fix here is to simply move that data loading operation to where it's needed. It turns out that models with high resolution data _do not_ have …
> relocate data loading in standardize-gcm

- CHANGELOG.md
- dodola/core.py
Increases the maximum temperature allowed by validation for tasmin and tasmax to 377 K. Without this change validation checks fail output from HadGEM3-GC31-11 (see https://github.com/ClimateImpactLab/downscaleCMIP6/issues/558) and UKESM1-0-LL (see https://github.com/ClimateImpactLab/downscaleCMIP6/issues/559).
It appears that UKESM1.0-LL SSP126 has a maximum daily value of 376.37 K.
> Increase max allowed tasmin, tasmax in services.validate to 377 K for UKESM1-0-LL

- CHANGELOG.md
- dodola/core.py
- dodola/services.py
Fixes `dodola validate-dataset` failing with out-of-memory errors on small workers without external dask cluster. This was especially a problem on quality-control checks to 0.25 degree grid input data. 
This solution is somewhat hackish in that we're reading and subsetting the input data to year available year in `dodola.services` — essentially refactoring the larger validation flow from `dodola.core` to `dodola.services` so that we can keep all the storage I/O implementation details out of `dodola.core`. This is an adaptation of the solution to used in [this temporary fix](https://github.com/ClimateImpactLab/downscaleCMIP6/blob/18cf791d4c169e707d4ae072cd4c217f65658421/workflows/templates/qualitycontrol-check-cmip6.yaml).
> Hack fix to validate OOM errors

- .github/workflows/buildpushrelease.yaml
Add ghactions job pushing to the public Github Container Registry (at `ghcr.io/climateimpactlab/dodola`) on releases.
> Add CI/CD job for releases to GHCR

- .github/workflows/test.yaml
- CHANGELOG.md
- environment.yaml
Adds to CI config so container tests report test coverage to codecov.
> Add test coverage reporting for CI container tests

- .github/workflows/buildpush.yaml
- .github/workflows/buildpushrelease.yaml
- .github/workflows/test.yaml
- CHANGELOG.md
- Dockerfile
- Makefile
- environment.yaml
- pyproject.toml
- setup.cfg
Quite a few big and potentially breaking changes in this PR.
- The container's parent image has changed from `continuumio/miniconda3:4.10.3` to `mambaorg/micromamba:0.23.0`. Hopefully this will help make the container lighter, faster, and more secure. This is a breaking change because this uses a different entrypoint in the container -- meaning that any users running this as part of an Argo Workflow with an Emissary executor will _likely_ need to update the `....container.command` used by the template to `["/usr/local/bin/_entrypoint.sh", "dodola"]`. I've noted this in the CHANGELOG.
- Most of the package specs, including the basic dependencies have been migrated from `setup.cfg` to `pyproject.toml`. setuptools now has experimental support for `pyproject.toml` so we should take advantage …
> Migrate container to micromamba, setup.cfg to pyproject.toml, and add metadata labels to container

- .github/workflows/docs.yaml
- CHANGELOG.md
- Makefile
- README.md
- dodola/__init__.py
- pyproject.toml
Adds automated doc builds/deploy with [pdoc](https://pdoc.dev/). Changes should be deployed to https://climateimpactlab.github.io/dodola/ on pushes to `main`.
We'll try this out and see how it goes.
> Add docs with pdocs CD workflow to Github Pages

- CHANGELOG.md
- pyproject.toml
- setup.cfg
Updates package metadata.
- Loosens abstract dependency pins. These were too tight, to begin with. Note these are the abstract dependencies for the dodola python package and not the environment pins in the deployed container.
- Updates package metadata URLs.
- Updates package metadata classifiers.
- The dodola python package now versions itself on install dynamically based on git hashes and tags. It falls back on version "999" when it builds and git data is not available (e.g. in the containers).
In addition, this fixes the `flake8` config so that it avoids checking build artifacts.
> Update pkg metadata

- environment.yaml
`xclim` has recently failed to import `pint.unit` in CI tests. Pinning to earlier version of `pint` (pint < 0.20.0) sub-dependency to work around this without radically changing how we handle dependencies and environment builds.
Examples of this failure:
https://github.com/ClimateImpactLab/dodola/actions/runs/3410997828/jobs/5674649890
https://github.com/ClimateImpactLab/dodola/actions/runs/3322139201/jobs/5490744399
from PR #212 and PR #213.
I don't think this will change the way the package runs. This is an internal maintenance thing.
> Fix broken pint use in xclim

- environment.yaml
Add and pin esmf to environment file. Pinning it to version just before it breaks compatibility with the version of xesmf we're running.
Considering conda-lock.
[summarize your pull request here]
> Fix broken env from esmf/xesmf

- dodola/core.py
- dodola/tests/test_core.py
- dodola/tests/test_services.py
Recently `black` has broke backwards compatibility with its style changes, causing our simple CI linting checks to fail PRs. This PR updates the code style with a newer version of `black` to clear up the CI failures.
This should have no impact on functionality.
> Minor format updating with black 23.1.0.

- CHANGELOG.md
- README.md
- dodola/cli.py
- dodola/core.py
- dodola/services.py
- dodola/tests/test_core.py
- dodola/tests/test_services.py
- pyproject.toml
We've been slopping about calling the method "bias correction" or "bias adjustment" interchangeably. Some have been confused by this. Would like to be more consistent. This PR updates several cases in docs and comments to use "adjustment".
> Update docs, comments language to be more consistent.
